name: "[Empty Repo] - Criação de Repositório"

description: Criação de repositório vazio, sem stack e deploys configurados!
title: "Criação de repositório vazio"
labels: ["repositorio","empty-repo"]

assignees:
 - ${{github.author}}

body:
  - type: markdown
    attributes:
      value: 
        Formulário padrão para criação de repositório no Github NTTData
  - type: input
    attributes:
      label: ">>Sigla do Produto<<"
      description: Sigla do Produto
      placeholder: DA
    validations:
      required: true 
  - type: input
    attributes:
      label: ">>Nome da Aplicação<<"
      description: Nome da Aplicação ou Produto
      placeholder: nomedaminhaaplicação
    validations:
      required: true 
  - type: dropdown
    attributes:
      label: ">>Templates<<"
      description: Este repositório é para qual recurso?
      options:
        - nttdata-pip-template-modules
    validations:
      required: true 

