name: "[INFRA] Criação de Terraform Modulos"
description: Criação de repositório para criação Terraform Modulos"
title: Criação de Repositório Terraform Modulos
labels: ["infra","repositorio"]
assignees:
  - ${{github.author}}
body:
  - type: markdown
    attributes:
      value: 
        Formulário padrão para criação de repositório Terraform Modulos no Github NTTData
  - type: input
    attributes:
      label: ">>Modulo<<"
      description: Digite o nome do modulo
      placeholder: nomemodulo
    validations:
      required: true 
  - type: dropdown
    attributes:
      label: ">>Templates<<"
      description: Selecione o template desejado?
      options:
        - nttdata-template-modules-terraform
    validations:
      required: true 
  