name: "[Terraform Modules AWS] Criação do Terraform Modules AWS"
description: Criação de repositório para criação Terraform Modules AWS"
title: Criação de Repositório Terraform Modules AWs
labels: ["infra","repositorio"]
assignees:
  - ${{github.author}}

body:
  - type: markdown
    attributes:
      value: 
        Formulário padrão para criação de repositório Terraform AWS no Github NTTData
  - type: input
    attributes:
      label: ">>Service<<"
      description: Service AWS 
      placeholder: ec2
    validations:
      required: true 
  - type: dropdown
    attributes:
      label: ">>Templates<<"
      description: Selecione o template desejado?
      options:
        - nttdata-template-modules-terraform
    validations:
      required: true 
  